[package]
name = "jieba_rs"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
publish = false

[lib]
crate-type = ["staticlib"]
name = "jieba_rs"

[[bin]]
name = "document"
path = "document.rs"

[dependencies]
ahash = "0.8"
cidian-rs = "0.1"
extendr-api = "0.9"
jieba-rs = { version = "0.10", features = ["textrank", "tfidf"] }
rayon = "1.12"

[lints.clippy]
expect_used = "deny"
unwrap_used = "deny"

[lints.rust]
warnings = "deny"

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
